### ISSUE TITLE
Custom Icon Not Working

### ISSUE THREAD

**Issue by mdezzi** [Armaell/home-assistant-custom-icons-loader#3]
I installed this plugin via HACS, added the line to the config file, created the "custom_icons" folder and inserted 1 svg icon in the folder. 

When i reboot, i see "file 'custom_icons/table_lamp.svg' unsupported" in my log followed by "no icons loaded for group 'custom'"

The icon i am using is a lamp icon from the philips hue icon pack in [this thread](https://community.home-assistant.io/t/implement-some-custom-icons-ive-created/13884/28). I have previously used this icon via the python script in [this post](https://community.home-assistant.io/t/implement-some-custom-icons-ive-created/13884/41) which i believe was created from thomasloven's Fontawesome plugin, so i know it works. 

Any suggestions to get it to work with this plugin?

**Comment by mdezzi** [comment]
I figured this out. The instructions for this component need to be clarified. 

For anyone who is having issues:
1. find an svg or multiple svgs
2. go to fontello.com
3. drag the svg icons onto the page to add them to the custom icons. 
4. click each one to set its default (css) name (this will be how you call it in HA)
5. select all the custom icons and click "Download Webfont" in the top right corner
6. save the ZIP file on your HA machine int he custom_icons folder. 
7. Reboot HA, you will notice that the zip file has been renamed to an svg file (leave it). 
8. call the new icons with "custom:<default css name here>" I have seen issues where i needed to clear the browser cache to get new icons to show.

**Comment by atterdal** [comment]
This does not work for me. Is it a docker thing?

**Comment by gdreelin** [comment]
No not a docker thing it is a plug-in issue. I am having the same issue too. Followed the directions to the letter and tried tinkering around with different ways to put the files into it but still no joy. I would really love to have this working. This is something I have been pushing for, for years now. I have used Fontastic for websites before and its like Fontello but you can make your own icon packs.

**Comment by gdreelin** [comment]
>     8\. call the new icons with "custom:" I have seen issues where i needed to clear the browser cache to get new icons to show.

I will give this a try to see if it works.

**Comment by gdreelin** [comment]
> 
> 
> > ```
> > 8\. call the new icons with "custom:" I have seen issues where i needed to clear the browser cache to get new icons to show.
> > ```
> 
> I will give this a try to see if it works.

Ok I followed the steps and dang it worked....thanks!!

**Comment by migo-dev** [comment]
If this isn't working for anyone; leave the folder name in fontello empty..

**Comment by daekka** [comment]
In the installation process, when I restart Home Assistant. This error occurs:
`Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/setup.py", line 170, in _async_setup_component
    result = await component.async_setup(  # type: ignore
  File "/home/homeassistant/.homeassistant/custom_components/custom_icons/__init__.py", line 10, in async_setup
    if parser.checkIfNeeded():
  File "/home/homeassistant/.homeassistant/custom_components/custom_icons/parser.py", line 62, in checkIfNeeded
    mkdir(ICONS_PATH)
PermissionError: [Errno 13] Permission denied: 'custom_icons/'`

I use: HASSBIAN - Home Assistant 0.108.6

**Comment by gdreelin** [comment]
Been working for me following the steps I posted above. I have create many custom icons that I have uploaded too and they work too.

**Comment by sheminasalam** [comment]
I tried the steps but it didn't work for me

**Comment by com-xuonghuynh** [comment]
not work

**Comment by mdezzi** [comment]
This component does not work as of how 0.110+ handles icons.

**Comment by ur7x** [comment]
Not working for me either... Created custom_icons in the root put the zip file there... nada.... tried putting the zip file in the custom_icons folder under custom_components...  nada... any ideas? 

Installed via HACS.
