### ISSUE TITLE
Item Blacklisted?

### ISSUE THREAD

**Issue by gdreelin** [Armaell/home-assistant-custom-icons-loader#6]
Is this project gone? I tried to add it back into HA but it says "Repository Blacklisted". That sucks this was nice to have using custom icons.

**Comment by jsiemek** [comment]
In 0.111, if I remember correctly, method of loading icons has changed.
This works no more.
Look at discussion in this repository for solution:
https://github.com/Armaell/home-assistant-custom-icons-loader/issues/5 

 It works, but way is a bit longer:

![icons](https://user-images.githubusercontent.com/36767404/96748580-00a3fa00-13ca-11eb-92e0-f0f33e022288.png)

**Comment by gdreelin** [comment]
> 
> 
> In 0.111, if I remember correctly, method of loading icons has changed.
> This works no more.
> Look at discussion in this repository for solution:
> #5
> 
> It works, but way is a bit longer:
> 
> ![icons](https://user-images.githubusercontent.com/36767404/96748580-00a3fa00-13ca-11eb-92e0-f0f33e022288.png)

Thanks for the update.
